### ISSUE TITLE
proposal: schema generation

### ISSUE THREAD

**Issue by jnathanh** [fraugster/parquet-go#32]
I'd like to add easy entry-level access to creation and parsing of parquet files without a developer needing to understand the details of building a schema definition. There are common sense default parquet types for each go type and we could easily build those default types for a given object type.

The target api would be something like this:
```golang
	type MyType {
		Int int
		Bool bool
		Slice []int
		// other common fields...
	}

	schemaDef, err := parquetschema.Generate(new(MyType))
	require.NoError(t, err)

	var buf bytes.Buffer
	w := NewWriter(goparquet.NewFileWriter(&buf,
		goparquet.WithCompressionCodec(parquet.CompressionCodec_SNAPPY),
		goparquet.WithSchemaDefinition(schemaDef),
	))

	// ...
```

**Comment by panamafrancis** [comment]
Hey @jnathanh thank you for proposing this feature! We just merged the PR from @akrennmair which implemented in the way that we wanted, but as a thank you for proposing it and doing the leg work with your implementation I would like to add you as an honorary contributor otherwise you won't show up in the github contributor graph. Does that sound OK to you?

**Comment by jnathanh** [comment]
@panamafrancis sure that sounds good. Thanks for adding the feature!

**Comment by panamafrancis** [comment]
done
